DEMO_APPLICATIONS = [
    {
        "company": "Acme Technologies",
        "role_title": "Customer Operations Manager",
        "date_applied": "2026-05-20",
        "status": "In Progress",
        "cv_route": "Operations",
        "fit_score": 4,
        "location": "Remote",
        "source": "Demo board",
        "last_contact_date": "2026-05-25",
        "next_action": "Send a polite follow-up",
        "notes": "Fictional demo record for an active application.",
        "tags": "demo, active",
    },
    {
        "company": "Northstar Digital",
        "role_title": "Implementation Lead",
        "date_applied": "2026-05-05",
        "status": "Interview",
        "cv_route": "Service Delivery",
        "fit_score": 4.5,
        "location": "Hybrid",
        "source": "Demo referral",
        "last_contact_date": "2026-05-28",
        "follow_up_date": "2026-06-05",
        "next_action": "Prepare interview notes",
        "notes": "Fictional demo record showing interview-stage tracking.",
        "tags": "demo, interview",
    },
    {
        "company": "FutureStack",
        "role_title": "Platform Programme Manager",
        "date_applied": "2026-04-12",
        "status": "Rejected",
        "cv_route": "General",
        "fit_score": 3.5,
        "location": "London",
        "source": "Demo listing",
        "last_contact_date": "2026-04-25",
        "outcome_date": "2026-04-25",
        "rejection_reason": "Fictional rejection reason for demo use only.",
        "notes": "Fictional demo record showing a closed rejection outcome.",
        "tags": "demo, rejected",
    },
    {
        "company": "BluePeak Systems",
        "role_title": "Service Delivery Director",
        "date_applied": "2026-04-20",
        "status": "Ghosted",
        "cv_route": "Service Delivery",
        "fit_score": 4,
        "location": "Remote",
        "source": "Demo recruiter",
        "last_contact_date": "2026-04-22",
        "outcome_date": "2026-05-14",
        "next_action": "Archive unless contact resumes",
        "notes": "Fictional demo record showing a ghosted closed outcome.",
        "tags": "demo, ghosted",
    },
    {
        "company": "Acme Technologies",
        "role_title": "Partner Success Lead",
        "date_applied": "2026-04-02",
        "status": "In Progress",
        "cv_route": "Operations",
        "fit_score": 4,
        "location": "Hybrid",
        "source": "Demo board",
        "last_contact_date": "2026-05-30",
        "next_action": "Track new hiring-manager update",
        "notes": "Fictional demo record showing a role reopened after contact.",
        "tags": "demo, reopened",
    },
]
